version: '2'
services:
  kanboard:
    build:
      context: .
      args:
        VERSION: 1.2.22
    image: kanboard:1.2.22
    container_name: kanboard
    restart: unless-stopped
    ports:
     - "8080:80"
    volumes:
     - kanboard_data:/var/www/app/data
     - kanboard_plugins:/var/www/app/plugins
     - kanboard_ssl:/etc/nginx/ssl
volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
  kanboard_ssl:
    driver: local
